version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: stepbook_user
      POSTGRES_PASSWORD: stepbook
      POSTGRES_DB: stepbook
    ports:
      - "65432:5432"
