version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: stepbook_user
      POSTGRES_PASSWORD: stepbooks
      POSTGRES_DB: stepbooks
    ports:
      - "65432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"