# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://non-prod-db.czvfgexghsct.rds.cn-north-1.amazonaws.com.cn:5432/stepbook
    username: novlnovl_user
    password: novlnovl

logging:
  level:
    org.springframework.web: DEBUG

aws:
  s3:
    bucket: stepbook.stage
  cdn: https://ds2rcorotrbeb.cloudfront.net
