# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stepbook?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: step_user
    password: step_ps
  data:
    redis:
      cluster:
        nodes:
          - clustercfg.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
      database: 0

server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.web: INFO

aws:
  s3:
    bucket: stepbook
    public-bucket: stepbook-public
  cdn: https://asset-stage.stepbooks.net

in-app-purchase:
  verify-host:
    ios: https://buy.itunes.apple.com
    android: https://androidpublisher.googleapis.com

stepbooks:
  mnp-qrcode-host: https://api.stepbooks.net/mnp-qrcode