# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://stepbook.czvfgexghsct.rds.cn-north-1.amazonaws.com.cn:5432/stepbook_prd?ssl=true&sslrootcert=/app/rds-cert.pem&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: stepbook_prd
    password: 1u1PiUa$yG28
  data:
    redis:
      cluster:
        nodes:
          - stepbook-prod-redis-cluster.retsq2.clustercfg.cnn1.cache.amazonaws.com.cn:6379
      database: 0


server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.web: INFO

aws:
  s3:
    bucket: stepbook-prod-private
    public-bucket: stepbook-prod-public
  cdn: https://s3.cn-north-1.amazonaws.com.cn

stepbooks:
  mnp-qrcode-host: https://api.stepbooks.net/mnp-qrcode
  admin-email: dongzhen1002@126.com
  order-export-cron: 0 5 15 * * ?

wechat:
  merchant:
    pay-notify-url: https://api.stepbooks.net/v1/payments/wechat/pay/callback
    refund-notify-url: https://api.stepbooks.net/v1/payments/wechat/refund/callback

wdt:
  app-key: bywh002-gw
  app-secret: 886f8b1e892dd764c97e226223b1ecce
  sid: bywh002
  base-url: https://api.wangdian.cn/openapi2/
  shop-no: 25
  platform-id: 127
