# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://non-prod-db.czvfgexghsct.rds.cn-north-1.amazonaws.com.cn:5432/stepbook_stage?ssl=true&sslrootcert=/app/rds-cert.pem
    username: stepbook_user
    password: 17@6WI4zcA
  data:
    redis:
      cluster:
        nodes:
          - clustercfg.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
#          - nonprod-stepbook-redis-cluster-0001-001.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
#          - nonprod-stepbook-redis-cluster-0001-002.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
#      host: clustercfg.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn
#      port: 6379
      database: 0


server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.web: DEBUG

aws:
  s3:
    bucket: stepbook.stage
    public-bucket: stepbook.public
  cdn: https://d1wf51uw2ybdc9.cloudfront.net

stepbooks:
  mnp-qrcode-host: https://api-stage.stepbooks.net/mnp-qrcode