# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/stepbook
    username: stepbook_user
    password: stepbook
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.springframework.web: DEBUG

aws:
  s3:
    bucket: stepbook.stage
    public-bucket: stepbook.public
  cdn:
#  cdn: https://ds2rcorotrbeb.cloudfront.net

stepbooks:
  mnp-qrcode-host: https://api-stage.stepbooks.net/mnp-qrcode