# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stepbook_prd?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: stepbook_user
    password: 111111
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.springframework.web: DEBUG

aws:
  s3:
    bucket: stepbook-stage
    public-bucket: stepbook-public
  cdn: https://s3.cn-north-1.amazonaws.com.cn

#  cdn: https://ds2rcorotrbeb.cloudfront.net

stepbooks:
  mnp-qrcode-host: https://api-stage.stepbooks.net/mnp-qrcode
  mock: 1
  admin-email: dongzhen1002@126.com
  order-export-cron: 0 5 15 * * ?
