# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/stepbook
    username: stepbook_user
    password: stepbook

logging:
  level:
    org.springframework.web: DEBUG

aws:
  s3:
    bucket: stepbook.stage
  cdn: https://ds2rcorotrbeb.cloudfront.net
