# DataSource Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stepbook
    username: step_user
    password: step_ps
  data:
    redis:
      cluster:
        nodes:
          - clustercfg.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
      #          - nonprod-stepbook-redis-cluster-0001-001.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
      #          - nonprod-stepbook-redis-cluster-0001-002.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn:6379
      #      host: clustercfg.nonprod-stepbook-redis-cluster.retsq2.cnn1.cache.amazonaws.com.cn
      #      port: 6379
      database: 0

server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.web: INFO

aws:
  s3:
    bucket: stepbook.production
    public-bucket: stepbook.production.public
  cdn: https://novlshared.s3.ap-northeast-1.amazonaws.com

in-app-purchase:
  verify-host:
    ios: https://buy.itunes.apple.com
    android: https://androidpublisher.googleapis.com

stepbooks:
  mnp-qrcode-host: https://api.stepbooks.net/mnp-qrcode