package net.stepbooks.domain.order.enums;

public enum OrderEvent {
    PLACE_SUCCESS,
    PAYMENT_SUCCESS,
    REFUND_APPROVE,
    REFUND_REJECT,
    REFUND_REQUEST,

    SHIP_SUCCESS,
    SHIPPED_TO_REFUND,
    RECEIVED_SUCCESS,

    USER_MANUAL_CANCEL,
    PAYMENT_TIMEOUT,

    ADMIN_MANUAL_CLOSE,
    REFUND_SUCCESS,
}
