package net.stepbooks.domain.order.enums;

public enum OrderEvent {
    PLACE_SUCCESS,
    PAY_SUCCESS,
    PAY_FAILED,
    SHIP_SUCCESS,
    DELIVER_SUCCESS,
    DELIVERED_TO_REFUND_SUCCESS,
    REFUND_TO_CLOSE_SUCCESS,
    USER_MANUAL_CANCEL_SUCCESS,
    ADMIN_MANUAL_CANCEL_SUCCESS,
    PAYMENT_TIMEOUT_CANCEL_SUCCESS,
    CLOSE_SUCCESS,
    INIT_TO_CLOSE_SUCCESS,
    PLACED_TO_CLOSE_SUCCESS,
    PAID_TO_CLOSE_SUCCESS,
    SHIPPED_TO_CLOSE_SUCCESS,
    DELIVERED_TO_CLOSE_SUCCESS,
}
